#!/usr/bin/env bash
#fbterm -s 24
#source /usr/local/sdk/main.env
export INTSALL_SCRIPT="/installer"
export SDK_PLATFORM="/usr/local/sdk"



[ -z "$LANG" ] && LANG="en_US.UTF-8" || true
export VERSION="1.1"
export RED='\033[0;31m'
export GREEN='\033[0;32m'
export YELLOW='\033[1;33m'
export BLUE='\033[0;34m'
export PURPLE='\033[0;35m'
export CYAN='\033[0;36m'
export NC='\033[0m'
export BRIGHT_WHITE='\033[1;97m$*\033[0m'


# Начальное значение по умолчанию
LANG="en_US.UTF-8"
LANG_FILE="$HOME/.quasar-lang"

# Если есть сохранённый язык — загружаем его
if [ -f "$LANG_FILE" ]; then
    source "$LANG_FILE"
fi

export LANG
export LC_ALL="$LANG"
export LC_MESSAGES="$LANG"


info() { echo -e "${BLUE}[info]${NC} $1"; }
error() { echo -e "${RED}[error]${NC} ${1}                                           :("; }
success() { echo -e "${GREEN}[success]${NC} $1"; }

echo_m() { echo -e "\033[1;97m${1}\033[0m"; }

logo() {
    cat  "$SDK_PLATFORM/mainlogo.txt"
}

check_network() {
    if ping -c 3 -W 5 archlinux.org &>/dev/null; then
        info "network is working"
        return 0
    else
        info "network is not working, connecting to network"
        "$SDK_PLATFORM"/system/network || true
        return 1
    fi
}


start_install() {
	if [ -f /installer/run ]; then
		chmod +x /installer/run
		/installer/run
	else 
		error "RUN file is not found"
		echo "/installer/run is not found, please check install QuasarInstall" >> /usr/local/sdm/log/log_1.txt
		sleep 3
		logo && main_menu
	fi		
}

repart() {
	if [ -f /usr/local/sdk/auto/default.yaml ]; then
		    echo "Starting autoinstall..."
		if "$INSTALL_SCRIPT"/run --auto; then
			echo "Autoinstall succeeded. Rebooting in 5 seconds..."
			sleep 5
			reboot
		else
			echo "Autoinstall FAILED. Dropping to shell for debug."
			live_os
		fi
	else 
		info "Auto install is not found"
	fi
	pacman-key --init 
	pacman-key --populate artix
	pacman -Syy
	
}

chroot_option() {
	"$SDK_PLATFORM"/chroot/chroot.run
}

recovery_option() {
	"$SDK_PLATFORM"/recovery/recov.run
}

live_os() {
	bash 
	export PS1='\[\e]0;\u@\h: \w\a\]${quasar_chroot:+($quasar_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
}


main_menu() {
	echo_m "╔════════════════════════════════════════════════╗"
	echo_m "║  ###      SDK function              ###        ║"
	echo_m "║ [ 1 ] Chroot                                   ║"
	echo_m "║ [ 2 ] Install QuasarLinux                      ║"
	echo_m "║ [ 3 ] Recovery System (Timeshift)              ║"
	echo_m "║ [ 4 ] Live system                              ║"
	echo_m "║ [ 5 ] Language: ${LANG}                    ║"
	echo_m "║ [ 6 ] Support                                  ║"
	echo_m "║  ###      Power function            ###        ║"
	echo_m "║ [ 7 ] Shutdown                                 ║"
	echo_m "║ [ 8 ] Restart                                  ║"
	echo_m "╚════════════════════════════════════════════════╝"
	read -p "[1-8] >>> " choice
	case "$choice" in
		1) "$SDK_PLATFORM"/chroot/chroot.run ;;
		2) start_install ;;
		3) "$SDK_PLATFORM"/recovery/recov.run ;;
		4) live_os  ;;
		5) source "$SDK_PLATFORM/locale/main.sh" ;;
		6) "$SDK_PLATFORM/HelpCenter/main.sh" ;;
		7)
			echo "System will shutdown in 3 seconds..."
			sleep 3
			poweroff
			;;
		8)
			echo "System will restart in 3 seconds..."
			sleep 3
			reboot
			;;
		*)
		    error "choice in not found"
		    sleep 2
		    clear
		    logo && main_menu
		    ;;
	esac 
}		

main() {
	check_network
	repart
	while true; do
        clear
        logo && main_menu

        # Если была ошибка - ждем, потом продолжаем
        if [ $? -eq 0 ]; then
            sleep 1
        fi
    done
}
main
