#!/bin/bash
set -euo pipefail

clear
main() {
    prefix=$(dialog --title "Quasar-install" --menu "$SELECT_OPTION" 15 70 7 \
                1 "Custom" \
                2 "AI prefix" \
                3 "Gaming prefix" \
                4 "default prefix" \
                3>&1 1>&2 2>&3 3>&-)
    case $prefix in
        1) ../prefix/custom_install ;;
        2) ../prefix/ai.sh ;;
        3) ../prefix/gaming.sh ;;
        4) ../prefix/default.sh ;;
    esac
}
main
