#!/usr/bin/env bash
sleep 3
clear

chmod +x /installer/modules/* || true
SRC="/installer/wiki.qr"
WIKI_GITVERSE="$SRC/gitverse-mirror-wiki.txt"
WIKI="$SRC/github-wiki.txt"
paste "$WIKI" "$WIKI_GITVERSE"
read -n 1 -s -p "Press any key to continue..."

check_desp() {
    which dialog || pacamn -S dialog
    which curl || pacman -S curl
    which git || pacman -S git
    which mkfs.fat || pacman -S dosfstools
}


main() {
    check_desp
    echo "Installing QuasarLinux REV-1.3"
    bash /installer/modules/install.sh
}
main
