#!/bin/bash 
set -euo pipefail

runpacman() {
    chroot /mnt pacman -Sy --needed --noconfirm "$@"
}

waydroid() {

    runpacman lxc python nftables dnsmasq dbus-python
    paru -S waydroid-git --noconfirm
    paru -S waydroid-openrc --noconfirm
    
    sudo rc-update add waydroid-continer-manager default
    waydroid init

}

