#!/bin/bash

cd /installer/modules/userland
browser=$(dialog --title "Меню" --menu "Выберите браузер: " 15 70 8 \
    1  "Firefox" \
    2  "Chromium" \
    3  "Brave" \
    4  "Ungoogled_chromium" \
    5  "Librewolf" \
    6  "Tor browser" \
    7  "Yandex" \
    8  "Falkon" \
    9  "Zen" \
    10 "Opera"  \
    3>&1 1>&2 2>&3 3>&-)

case $? in
    0)
        case $browser in
            1)  ./browser_install firefox ;;
            2)  ./browser_install  chromium ;;
            3)  ./browser_install  brave ;;
            4)  ./browser_install  ungoogled_chromium ;;
            5)  ./browser_install  librewolf ;;
            6)  ./browser_install  torbrowser ;;
            7)  ./browser_install  yandex ;;
            8)  ./browser_install  falkon ;;
            9)  ./browser_install  zen ;;
            10) ./browser_install  opera ;;
        esac
        ;;
    *)
        clear
        echo "Выбор  браузера отменен."
        ;;
esac
