#!/bin/bash
set -euo pipefail


install_wine() {
    chroot /mnt /bin/sh << 'EOF'
    pacman -S wine winetricks --noconfirm
EOF

}

install_wine_staging() {
    chroot /mnt /bin/sh << 'EOF'
    pacman -S wine-staging winetricks --noconfirm

EOF

}

install_quasar_wine() {
    chroot /mnt /bin/sh << 'EOF'
    pacman -S wine-staging winetricks --noconfirm

    wineboot --init


    winetricks --force -q --unattended corefonts tahoma cjkfonts vcrun6 vcrun2003 vcrun2005 vcrun2008 vcrun2010 vcrun2012 vcrun2013 vcrun2015 vcrun2019 vcrun2022
    winetricks --force -q --unattended dotnet20 dotnet30 dotnet35 dotnet40 dotnet45 dotnet462 dotnet48 dotnetcoredesktop3 dotnetcoredesktop6
    winetricks --force -q --unattended d3dcompiler_43 d3dcompiler_47 d3dx9 d3dx10 d3dx11_43 directx9 directx10 directx11
    winetricks --force -q --unattended xact xinput quartz devenum wmp9 wmp10 wmp11 msxml3 msxml4 msxml6 gdiplus
    winetricks --force -q --unattended riched20 riched30 vb6run mfc40 mfc42 mfc70 mfc80 mfc90 mfc100 mfc110 mfc140
    winetricks --force -q --unattended ie8 flash silverlight physx openal dsound xna40 faudio dxvk vkd3d dgvoodoo2 win10
EOF
}

install_wine_ge() {
    chroot /mnt /bin/sh << 'EOF'
    mkdir -p ~/.apps || exit 1
    cd ~/.apps || exit 1

    wget -P /tmp https://github.com/GloriousEggroll/wine-ge-custom/releases/download/GE-Proton8-26/wine-lutris-GE-Proton8-26-x86_64.tar.xz
    tar -xf /tmp/wine-lutris-GE-Proton8-26-x86_64.tar.xz
    mv lutris-GE-Proton8-26-x86_64 wine-ge

    # Добавляем в PATH для текущего пользователя

    mkdir -p ~/.config/environment.d
    echo "PATH=~/.apps/wine-ge/bin:\$PATH" > "~/.config/environment.d/wine-ge.conf"
    echo "XDG_DATA_DIRS=~/.apps/wine-ge/share:\$XDG_DATA_DIRS" >> "~/.config/environment.d/wine-ge.conf"


    # Инициализируем wine от имени пользователя

    env PATH="~/.apps/wine-ge/bin:$PATH" wineboot --init

    echo "Wine-GE установлен и настроен!"
EOF

}


install_portproton() {
    chroot /mnt /bin/sh << 'EOF'
    flatpak install flathub portproton -y
EOF
}


main() {
    local wine="$1"
    case "$wine" in
        default) install_wine ;;
        staging) install_wine_staging ;;
        staging_full) install_quasar_wine ;;
        ge-version) install_wine_ge ;;
        portproton) install_portproton ;;
        *) exit 1
    esac
}
main "$@"
