#!/bin/bash

SCRIPT_DIR="/installer/modules"
chmod +x "$SCRIPT_DIR"
express() {
    "$SCRIPT_DIR"/parted
    "$SCRIPT_DIR"/basepack
    regions
    "$SCRIPT_DIR"/mirrorconfig.sh
    "$SCRIPT_DIR"/inst_pack
    "$SCRIPT_DIR"/users.sh
    "$SCRIPT_DIR"/bootloader

}

regions() {
    cd "$SCRIPT_DIR"
    cp region_settings /mnt
    cp region /mnt
    fast-chroot /mnt /region_settings
}

parted_menu() {
    "$SCRIPT_DIR"/parted
}

user() {
    "$SCRIPT_DIR"/users.sh
}

while true; do
    seting=$(dialog --title "Quasar-install" --menu "$MENU_SELECT_OPTION" 15 70 7 \
        1 "$EXPRESS_SETUP" \
        2 "$PARTITIONING" \
        3 "$INSTALL_BASE" \
        4 "$INSTALL_PACKAGES" \
        5 "$USER_SETUP" \
        6 "$INSTALL_BOOTLOADER" \
        7 "$EXIT" \
        3>&1 1>&2 2>&3 3>&-)

    [ $? -ne 0 ] && break   # если жмём ESC/Cancel → выход

    case $seting in
        1) express ;;
        2) parted_menu ;;
        3) "$SCRIPT_DIR/basepack" ;;
        4) "$SCRIPT_DIR/inst_pack" ;;
        5) user ;;
        6) "$SCRIPT_DIR/bootloader" ;;
        7) break ;;
    esac
done
