#!/bin/bash


Europe() {
    # Получаем список файлов (регионов)
    regions=($(ls /mnt/usr/share/zoneinfo/Europe/))

    # Формируем строку для dialog (tag, item, status)
    checklist_items=()
    for region in "${regions[@]}"; do
        checklist_items+=("$region" "$region" "off")
    done

    # Вызываем dialog с checklist
    selected=$(dialog --stdout --radiolist "Выберите регионы:" 30 40 10 \
      "${checklist_items[@]}")

    clear
    sudo ln -s /usr/share/zoneinfo/Europe/"$selected" /mnt/etc/localtime
}
Asia() {
    # Получаем список файлов (регионов)
    regions=($(ls /mnt/usr/share/zoneinfo/Asia/))

    # Формируем строку для dialog (tag, item, status)
    checklist_items=()
    for region in "${regions[@]}"; do
        checklist_items+=("$region" "$region" "off")
    done

    # Вызываем dialog с checklist
    selected=$(dialog --stdout --radiolist "Выберите регионы:" 30 40 10 \
      "${checklist_items[@]}")

    clear
    sudo ln -s /usr/share/zoneinfo/Asia/"$selected" /mnt/etc/localtime
}
US() {
    regions=($(ls /mnt/usr/share/zoneinfo/America/))

    # Формируем строку для dialog (tag, item, status)
    checklist_items=()
    for region in "${regions[@]}"; do
        checklist_items+=("$region" "$region" "off")
    done

    # Вызываем dialog с checklist
    selected=$(dialog --stdout --radiolist "Выберите регионы:" 30 40 10 \
      "${checklist_items[@]}")

    clear
    sudo ln -s /usr/share/zoneinfo/America/"$selected" /mnt/etc/localtime
}

Africa() {
    regions=($(ls /mnt/usr/share/zoneinfo/Africa/))

    # Формируем строку для dialog (tag, item, status)
    checklist_items=()
    for region in "${regions[@]}"; do
        checklist_items+=("$region" "$region" "off")
    done

    # Вызываем dialog с checklist
    selected=$(dialog --stdout --radiolist "Выберите регионы:" 30 40 10 \
      "${checklist_items[@]}")

    clear
    sudo ln -s /usr/share/zoneinfo/Africa/"$selected" /mnt/etc/localtime
}
Antarctica() {
    regions=($(ls /mnt/usr/share/zoneinfo/Antarctica/))

    # Формируем строку для dialog (tag, item, status)
    checklist_items=()
    for region in "${regions[@]}"; do
        checklist_items+=("$region" "$region" "off")
    done

    # Вызываем dialog с checklist
    selected=$(dialog --stdout --radiolist "Выберите регионы:" 30 40 10 \
      "${checklist_items[@]}")

    clear
    sudo ln -s /usr/share/zoneinfo/Antarctica/"$selected" /mnt/etc/localtime
}

Arctic() {
    regions=($(ls /mnt/usr/share/zoneinfo/Arctic/))

    # Формируем строку для dialog (tag, item, status)
    checklist_items=()
    for region in "${regions[@]}"; do
        checklist_items+=("$region" "$region" "off")
    done

    # Вызываем dialog с checklist
    selected=$(dialog --stdout --radiolist "Выберите регионы:" 30 40 10 \
      "${checklist_items[@]}")

    clear
    sudo ln -s /usr/share/zoneinfo/Arctic/"$selected" /mnt/etc/localtime
}

Atlantic() {
    regions=($(ls /mnt/usr/share/zoneinfo/Atlantic/))

    # Формируем строку для dialog (tag, item, status)
    checklist_items=()
    for region in "${regions[@]}"; do
        checklist_items+=("$region" "$region" "off")
    done

    # Вызываем dialog с checklist
    selected=$(dialog --stdout --radiolist "Выберите регионы:" 30 40 10 \
      "${checklist_items[@]}")

    clear
    sudo ln -s /usr/share/zoneinfo/Atlantic/"$selected" /mnt/etc/localtime
}

Australia() {
    regions=($(ls /mnt/usr/share/zoneinfo/Australia/))

    # Формируем строку для dialog (tag, item, status)
    checklist_items=()
    for region in "${regions[@]}"; do
        checklist_items+=("$region" "$region" "off")
    done

    # Вызываем dialog с checklist
    selected=$(dialog --stdout --radiolist "Выберите регионы:" 30 40 10 \
      "${checklist_items[@]}")

    clear
    sudo ln -s /usr/share/zoneinfo/Australia/"$selected" /mnt/etc/localtime
}

Brazil() {
    regions=($(ls /mnt/usr/share/zoneinfo/Brazil/))

    # Формируем строку для dialog (tag, item, status)
    checklist_items=()
    for region in "${regions[@]}"; do
        checklist_items+=("$region" "$region" "off")
    done

    # Вызываем dialog с checklist
    selected=$(dialog --stdout --radiolist "Выберите регионы:" 30 40 10 \
      "${checklist_items[@]}")

    clear
    sudo ln -s /usr/share/zoneinfo/Brazil/"$selected" /mnt/etc/localtime
}

Canada() {
    regions=($(ls /mnt/usr/share/zoneinfo/Canada/))

    # Формируем строку для dialog (tag, item, status)
    checklist_items=()
    for region in "${regions[@]}"; do
        checklist_items+=("$region" "$region" "off")
    done

    # Вызываем dialog с checklist
    selected=$(dialog --stdout --radiolist "Выберите регионы:" 30 40 10 \
      "${checklist_items[@]}")

    clear
    sudo ln -s /usr/share/zoneinfo/Canada/"$selected" /mnt/etc/localtime
}

Etc() {
    regions=($(ls /mnt/usr/share/zoneinfo/Etc/))

    # Формируем строку для dialog (tag, item, status)
    checklist_items=()
    for region in "${regions[@]}"; do
        checklist_items+=("$region" "$region" "off")
    done

    # Вызываем dialog с checklist
    selected=$(dialog --stdout --radiolist "Выберите регионы:" 30 40 10 \
      "${checklist_items[@]}")

    clear
    sudo ln -s /usr/share/zoneinfo/Etc/"$selected" /mnt/etc/localtime
}
case $1 in
    Europe) Europe ;;
    Asia) Asia ;;
    US) US ;;
    Africa) Africa ;;
    Antarctica) Antarctica ;;
    Arctic) Arctic ;;
    Atlantic) Atlantic ;;
    Australia) Australia ;;
    Brazil) Brazil ;;
    Canada) Canada ;;
    Etc) Etc ;;
    *) echo "Нету подходящего региона" ;;
esac
